config/routes.rb
Rails.application.routes.draw do
  resources :post_tags
  get '/login' => 'sessions#new'
  root 'application#index'
  get '/', to: 'application#index', as: 'q'

  get '/sign-up' => 'users#new'
  post '/sign-up' => 'users#create'

  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/login' => 'sessions#forbidden'

  resources :comments
  resources :tags
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
require 'carrierwave/orm/activerecord'
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :posts
  belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :comments
  has_many :posts_tag
  has_many :tags, through: :posts_tag

  # accepts_nested_attributes_for :tags
  # accepts_nested_attributes_for :posts_tag
  #belongs_to :user

  # def tags_attributes=(tag_attributes) #associates tag only if it doesn't already exist for the post
  #   tag_attributes.values.each do |tag_attribute|
  #     tag = Tag.find_or_create_by(tag_attribute)
  #     self.tags << tag
  #   end
  # end

  # def tag_id
  #   self.tags << tag.find(tag_id)
  # end

  def tag_names #helper method
    # gets tag names in an array
    self.tags.map { |tag| tag.name }
  end
end

app/models/post_tag.rb
class PostsTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/posts_tag.rb
class PostsTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts_tags
  has_many :posts, through: :posts_tag
end

app/models/tag_type.rb
class TagType < ApplicationRecord
  has_many :tags
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts
  has_many :comments
  has_secure_password


end

app/controllers/application_controller.rb
require 'bcrypt'
class ApplicationController < ActionController::Base

  def index
    @posts = if params[:q]
      Post.all.select do |post|
        tag_names = post.tag_names
        tag_names.include?(params[:q].capitalize) #all names are capitalized, needs refactor to be case compatable
      end
      # Post.where('post.tags.name LIKE ?', "%#{params[:q]}%")
    else
      Post.order('id DESC')
    end
  end

  private
  def post_params
    params.require(:post).permit(:q)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/post_tags_controller.rb
class PostTagsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order('created_at DESC')
  end

  def new
    @post = Post.new
    @tagcolors = Tag.all.select {|tag| tag.tag_type == 'Color'}
    @tagclothing = Tag.all.select {|tag| tag.tag_type != 'Color'}
  end

  def create
    @post = Post.new(post_params)
    # byebug
    if @post.save
      redirect_to posts_path
      # flash[:success] = "Book added"
    else
      render :new
      flash.now[:danger] = "Book NOT added"
    end

    # post = Post.create(params[:post])
    # uploader = ImageUploader.new
    # uploader.store!(params[:image])

    #redirect_to post_path(post)
  end

  def show
    @post = Post.find(params[:id])
    # @image = uploader.retrieve_from_store!()
  end

  private

  def post_params
    params.require(:post).permit(
      :image, tag_ids:[]
      # ,tags_attributes: [:name],
      # posts_tag_attributes: [:tag_id, :post_id]
    )
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    #byebug
    @user = User.find_by(email: params[:user][:email])
    if !@user #&& (!params[:user][:email] || params[:user][:email].empty?)
      redirect_to '/login'
    else
      #byebug
      # redirect_to :forbidden unless @user.authenticate(params[:password])
      # authenticated = @user.try(:authenticate, params[:password])
      # return head(:forbidden) unless authenticated

      session[:name] = @user.name
      byebug
      redirect_to user_path(@user)#(controller: 'users', action: 'show')
    end
  end

  def forbidden

  end

  def destroy
    session.delete :username
    redirect_to(controller: 'users', action: 'new')
  end



end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end

  def show
    @posts = Post.all
    @tag = Tag.find(params[:id])
    @posts_with_tag = @posts.select {|post| post.tags.include?(@tag)}
    #byebug
    # pass in info to show page and use post partial somehow
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    #byebug
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
      <!-- <b>Search Posts Tags:</b> -->
      <br><br><br><br>
      <br><br><br><br>
      <br><br><br><br>
      <%= form_tag '/', method: :get do %>
      <%= text_field_tag :q, params[:q], class: "search-bar", placeholder:"Search Posts Tags:" %>
      <%= submit_tag 'Search',class: "search-btn" %>
      <% end %></br></br>
      <h3 class="center-text">Today's Recent Posts</h3>
      <br>
      <%= render @posts %>

    </div>
    <div class="col-md-3">

    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<%= link_to post_path(post), :action => 'go' do %>
<div class="img-box">
  <%= image_tag(post.image.url, alt: 'Image', class: 'post-image img-responsive mx-auto') if post.image? %>
</div>
<% end  %>
<br>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <h1>Posts</h1>

      <%= link_to 'Add post', new_post_path %>

      <!-- iterates through @posts to generates partials -->
      <%= render @posts %>

    </div>
  </div>
</div>

app/views/posts/new-backup.html.erb
<%= form_for @post do |f| %>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div>
      <h3>Add Tags</h3>
      <h4>Choose a Type</h4>
      <%= f.fields_for :contributions do |builder| %>
      <%= builder.collection_select(:author_id, Author.all, :id, :full_name, prompt: "Select from existing authors") %>
      <% end %>
  </div>

  <%= f.collection_select(:tag_ids, Tag.all.select('distinct tag_type'), :id, :tag_type,
    {include_blank: false, :include_hidden => false, :selected => @post.tags.map(&:id)}
                           ) %>
  <%= f.collection_select(:tag_ids, Tag.all.select('distinct name'), :id, :name,
     {include_blank: false, :include_hidden => false, :selected => @post.tags.map(&:id)}
                            ) %>
                            <br>


  <%= f.submit "Upload Post" %>
<% end %>

app/views/posts/new.html.erb
<h3>New Post</h3>
<%= form_for @post do |f| %>

  <div>
    <%= f.label :image, "Upload Image:"%>
    <%= f.file_field :image %>
  </div>
  <br>
  <div>
      <h3>Add Tags</h3>
      <!-- <h4>Choose a Type</h4> -->

      <p>
        <%= f.label :tags %><br />
        <% for tag in Tag.all %>
          <%= check_box_tag "post[tag_ids][]", tag.id, @post.tags.include?(tag) %>
          <%=h tag.name %><br />
        <% end %>
      </p>

  </div>


  <br><br>


  <%= f.submit "Upload Post" %>
<% end %>

app/views/posts/show.html.erb
<%= link_to 'All posts', posts_path %>
<h1><%= @post.id %></h1>

<%= image_tag(@post.image.url, alt: 'Image') if @post.image? %>
<br>
<% @post.tag_names.each do |tag| %>
  <% tag_id = Tag.find_by(name: tag) %>
<%= link_to tag, tag_path(tag_id)%>
<% end %>

<p><%= link_to 'Edit', edit_post_path(@post) %></p>

app/views/tags/show.html.erb
<h2><%= @tag.name %> Posts</h2>

<% @posts_with_tag.each do |post|%>
<%= image_tag(post.image.url, alt: 'Image') if post.image? %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4" >
    </div>
    <div class="col-md-4 offset-md-4" >
      <h2>Current Users</h2>
      <% @users.each do |user| %>
      <%= link_to user.name, user_path(user), class:"" %>
      <br>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <h2 class="center-text">New User</h2>
      <%= form_for @user do |f| %>
        <br /><%= f.label :name %>
        <br>
        <%= f.text_field :name, class: "form-width"%>
      <br>
        <br /><%= f.label :username %>
        <br>
        <%= f.text_field :username, class: "form-width" %>
      <br>
        <br /><%= f.label :email %>
        <br>
        <%= f.text_field :email, class: "form-width" %>
      <br>
        <br /><%= f.label :Password %>
        <br>
        <%= f.password_field :password, class: "form-width" %>
      <br>
        <br /><%= f.label :Password_Confirmation %>
        <br>
        <%= f.password_field :password_confirmation, class: "form-width" %>
      <br>
      <br>
        <%= f.submit "Sign Up" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2><%= @user.name %></h2>
      Username: <%= @user.username %>
      <br>
      Email: <%= @user.email %>
      <br>
      <%= link_to "Create Post", new_post_path(@post) %>
    </div>
  </div>
</div>